"""The per-run report (Aldemir PLAN.md §10; shared in D103): generated into the run directory.

SECTIONS ARE A LIST OF BUILDERS, so a new figure or a new comparison is one entry rather than an
edit inside a monolithic function. Each builder takes `(spec, params, data)` and returns markdown
or None (None = nothing to say for this run, and the section is dropped).

The report states what a run does and does NOT license. That is not decoration: a study's fair
claims and unfair ones are separated by the specimen's own gaps (an invented protocol, an inferred
dimension, a second-hand test record), and a number quoted without them travels further than it
should. The specimen supplies those through `spec.sources` and `spec.licence`.
"""
from __future__ import annotations

from pathlib import Path

from . import metrics
from .spec import StudySpec


def _table(rows, header) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "|".join(["---"] * len(header)) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


# --- section builders ----------------------------------------------------------------------------

def s_header(spec, params, data) -> str:
    return (f"# {params['analysis']} — {spec.label(params)}\n\n"
            f"{spec.citation} Generated by `study/run.py`; parameter schema "
            f"v{params['schema_version']}.\n\n"
            f"* run directory: `{data.get('run_name', '?')}`\n"
            f"* built: {data.get('nodes', '?'):,} nodes / {data.get('elements', '?'):,} elements\n"
            f"* wall clock: {data.get('elapsed_s', 0):,.0f} s over {data.get('steps', 0):,} steps")


def s_parameters(spec, params, data) -> str:
    rows = []
    for name, value, default, affects in spec.registry.describe(params):
        src, why = spec.sources.get(name, ("", ""))
        mark = "" if value == default else " **(non-default)**"
        rows.append([f"`{name}`", f"{value}{mark}", affects, src, why])
    return ("## Parameters, with the source of each value\n\n"
            + _table(rows, ["parameter", "value", "affects", "source", "note"]))


def s_model(spec, params, data) -> str:
    m = data.get("meta", {})
    rows = [["panel", f"{m.get('panel_mm', ['?', '?'])[0]:.0f} x "
                      f"{m.get('panel_mm', ['?', '?'])[1]:.0f} x {m.get('thickness_mm', 0):.0f} mm"],
            ["drift denominator", f"{m.get('drift_denominator_mm', 0):.0f} mm"],
            ["nodes / elements", f"{m.get('nodes', 0):,} / {m.get('elements', 0):,}"],
            ["steel nodes (bond only)", f"{m.get('steel_nodes', 0):,}"],
            ["composition", m.get("describe", "")],
            ["strut life eps_ult/eps_cr", f"orthogonal {m.get('strut_life_orthogonal', 0):.1f}, "
                                          f"diagonal {m.get('strut_life_diagonal', 0):.1f}"],
            ["first cracking", f"V_cr = {m.get('V_cr_N', 0) / 1e3:.0f} kN at "
                               f"{m.get('drift_cr', 0):.4%} drift"]]
    if m.get("material_overrides"):
        o = m["material_overrides"]
        rows.append(["material overrides", f"fc {o['fc'][0]} -> {o['fc'][1]}, "
                                           f"ft {o['ft'][0]} -> {o['ft'][1]}, "
                                           f"epsc0 {o['epsc0'][0]:.6f} -> {o['epsc0'][1]:.6f} "
                                           f"({o['note']})"])
    note = ""
    if m.get("strut_life_orthogonal", 99) < 10:
        note = ("\n\n**Strut life below 10**: a strut fails almost immediately after cracking and "
                "the lattice cannot redistribute. WSH3 needed `--gf-factor 2` for exactly this "
                "(D67), and Gf is not a neutral knob (D75).")
    return "## The model as built\n\n" + _table(rows, ["", ""]) + note


def s_calibration(spec, params, data) -> str:
    m = data.get("meta", {})
    rows = [["calibrated strut area A_t", f"{m.get('area_mm2', 0):,.1f} mm²"],
            ["EA per strut", f"{m.get('EA_N', 0):.3e} N"],
            ["field", spec.calibration_note or m.get("field", "uniaxial")],
            ["Gf multiple implied by the tail", data.get("gf_multiple_note", "1.0 by construction "
                                                         "(`tail=solved`)")]]
    if data.get("k_over_continuum") is not None:
        rows.append(["K_lattice / K_continuum", f"{data['k_over_continuum']:.4f}  "
                                                f"— the Stage 2 gate: the balance claims to "
                                                f"reproduce a plane-stress continuum on the same "
                                                f"grid, and this is that claim measured"])
    if data.get("k_over_perfect") is not None:
        rows.append(["K / K_perfect (bond artefact)", f"{data['k_over_perfect']:.3f}"])
    return ("## Calibration\n\n" + _table(rows, ["", ""])
            + "\n\nThe energy balance is a HOMOGENIZATION, not a structural fit: continuum and "
              "lattice stored energy are equated under an affine strain field and one uniform EA "
              "falls out. No FE solve, no reference model, no optimiser (D47).")


def s_response(spec, params, data) -> str:
    if data.get("peak_shear") is None:
        return None
    refs = spec.references
    pk, pk_drift, smoothed = metrics.headline_peak(data)
    peak = pk / 1e3
    label = ("peak base shear (%g ms moving average)"
             % (data.get("peak_smoothing_window_s", metrics.WINDOW_S) * 1e3)) if smoothed \
        else "peak base shear"
    rows = [[label, f"{peak:,.1f} kN"],
            ["at drift", f"{pk_drift:.4%}"],
            [f"measured peak ({refs.f_source})", f"{spec.measured_F_kN:,.1f} kN"],
            ["model / test", f"{peak / spec.measured_F_kN:.3f}"],
            ["initial secant", f"{data.get('k_initial', 0) / 1e3:,.1f} kN/mm"],
            [f"measured K ({refs.k_source})", f"{spec.measured_K_kNmm:,.1f} kN/mm"],
            ["traced to", f"{data.get('end_drift', 0):.4%} drift "
                          f"(converged={data.get('converged')})"]]
    h = float(params["horizon"])
    if h in refs.author_by_horizon:
        k_a, f_a = refs.author_by_horizon[h]
        rows += [[f"{refs.author_label}'s own run at horizon {h:g}",
                  f"K {k_a:,.1f} kN/mm, F {f_a:,.1f} kN"],
                 ["his overshoot on force", f"{f_a / spec.measured_F_kN:.3f}"
                                            + (f" — {spec.author_note}" if spec.author_note else "")]]
    if data.get("peak_plateau"):
        lo, hi = data["peak_plateau"]
        # 0.02 drift-percentage-points is the line between a top a run genuinely resolves and one
        # where "drift at peak" is an argmax over a flat region.
        flat = (hi - lo) > 2e-4
        rows.append([f"peak plateau (within {data.get('peak_plateau_fraction', 0.005):.1%})",
                     f"{lo:.4%} .. {hi:.4%} drift — "
                     + ("FLAT TOP: 'drift at peak' is an argmax over this range, not a measurement"
                        if flat else
                        "a sharp peak, so 'drift at peak' above is a real measurement")])
    if data.get("drift_capacity") is not None:
        rows.append([f"drift capacity ({1 - data.get('capacity_drop', 0.2):.0%} of peak)",
                     f"{data['drift_capacity']:.4%}"])
    elif data.get("drift_capacity_note"):
        rows.append(["drift capacity", data["drift_capacity_note"]])
    note = metrics.ringing_note(data)
    tail = ""
    if smoothed:
        raw = data.get("peak_shear_raw", data.get("peak_shear")) / 1e3
        rows.append(["raw sample maximum", f"{raw:,.1f} kN at "
                                           f"{data.get('drift_at_peak_raw', 0):.4%} "
                                           f"({data.get('peak_ringing_ratio', float('nan')):.3f}x "
                                           f"the smoothed peak)"])
        tail = "\n\n" + (note or "")
    return "## Response\n\n" + _table(rows, ["", ""]) + tail


def s_residual(spec, params, data) -> str:
    dyn = data.get("dynamic_residual")
    if not dyn:
        return None
    peak = abs(metrics.headline_peak(data)[0] or 1.0)
    n_start = min(len(dyn) - 1, 10 * max(1, int(data.get("steps_per_period_used") or 40)))
    start = max(abs(d) for d in dyn[:n_start + 1])
    tail = dyn[n_start:] or dyn
    steady = max(abs(d) for d in tail)
    asc = data.get("residual_ascending_p95")
    rows = [["start-up transient", f"{start / 1e3:,.1f} kN, once, at near-zero drift"],
            ["steady maximum", f"{steady / 1e3:,.1f} kN = {steady / peak:.1%} of peak shear"]]
    if asc is not None:
        rows.append(["ascending branch, p95", f"{asc / 1e3:,.1f} kN = {asc / peak:.1%} of peak"])
    return ("## Inertia + damping riding in the recorded shear\n\n" + _table(rows, ["", ""])
            + "\n\nRead RELATIVELY, not absolutely (D62): the residual compares runs of the same "
              "runner. The ascending-branch figure is the one that says whether the PEAK is real "
              "resistance — a large headline number is usually the collapse transient.")


def s_figures(spec, params, data) -> str:
    figs = data.get("figures") or []
    if not figs:
        return None
    return "## Figures\n\n" + "\n".join(f"* `figures/{f}`" for f in figs)


def s_licence(spec, params, data) -> str:
    if spec.licence is None:
        return None
    fair, unfair = spec.licence(params)
    out = ["## What this run does and does not license", "", "**Fair:**"]
    out += [f"* {f}" for f in fair]
    out += ["", "**Not fair, and to be repeated wherever these numbers are quoted:**"]
    out += [f"* {k} — {v}" for k, v in unfair]
    return "\n".join(out)


def s_comparison(spec, params, data) -> str:
    rows = data.get("comparison")
    if not rows:
        return None
    refs = spec.references
    body = []
    for r in rows:
        body.append([f"{r['at_mm']:.2f}", f"{r['model_kN']:,.1f}",
                     f"{r.get('test_envelope_kN') or float('nan'):,.1f}",
                     f"{r.get('aydin_kN') or float('nan'):,.1f}",
                     f"{r.get('model_over_test') or float('nan'):.3f}",
                     f"{r.get('model_over_aydin') or float('nan'):.3f}",
                     "past the clip" if r["clipped"] else ""])
    return ("## Against the references, AT MATCHED DISPLACEMENT\n\n"
            + _table(body, ["u (mm)", "model (kN)", "test envelope", refs.author_label,
                            "model/test", f"model/{refs.author_label}", ""])
            + "\n\nCompared at matched displacement, never peak to peak: the model and the test "
              "reach their peaks at different drifts, so a peak/peak ratio compares two different "
              "states (D77)." + (f" {refs.note}" if refs.note else ""))


SECTIONS = (s_header, s_parameters, s_model, s_calibration, s_response, s_comparison, s_residual,
            s_figures, s_licence)


def write(spec: StudySpec, out: Path, params: dict, data: dict) -> Path:
    body = [s(spec, params, data) for s in SECTIONS]
    text = "\n\n".join(b for b in body if b) + "\n"
    path = out / "report.md"
    path.write_text(text)
    return path
